sqlite3:
  adapter: sqlite3
  database: rocket_tag.sqlite3

mysql:
  adapter: mysql2
  hostname: localhost
  username: rails
  password:
  database: rocket_tag
  charset: utf8
  
postgresql:
  adapter: postgresql
  hostname: localhost
  username: rails
  password:
  database: rocket_tag
  encoding: utf8
